#image: java:8
image: maven:3-jdk-8

variables:
  CF_APP: "scpcitestapp"
  CF_DOMAIN: "cfapps.eu10.hana.ondemand.com"
  CF_API: "https://api.cf.eu10.hana.ondemand.com"
  CF_PROD_ORGANIZATION: "S0018628687trial_S0018628687trialnew"
  CF_PROD_SPACE: "prod"
  CF_QA_ORGANIZATION: "S0018628687trial_S0018628687trialnew"
  CF_QA_SPACE: "qa"

stages:
  - build
  - staging
  - deploy

build:
  stage: build
  script: 
    - mvn install
  artifacts:
    paths:
      - /tmp/scpcitestapp.war

test:
  stage: staging
  script:
  - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
  # Login to Cloud Foundry
  - ./cf api $CF_API 
  # Use the cf api command to set the api endpoint
  - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -o $CF_QA_ORGANIZATION -s $CF_QA_SPACE
  - ./cf push -p /tmp/$CF_APP.war
  only:
  - master

production:
  stage: deploy
  script:
  - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
  # Login to Cloud Foundry
  - cf api $CF_API 
  # Use the cf api command to set the api endpoint
  - cf login -u $CF_USERNAME -p $CF_PASSWORD -o $CF_PROD_ORGANIZATION -s $CF_PROD_SPACE
  - cf push -p /tmp/$CF_APP.war
  only:
  - master
  when: manual