language: java
env:
  global:
  - matrix:
    - CXX=g++-4.8
    - CF_APP=scpcitestapp
  - secure: P5qCyd5tw9UFFC+UQETwQSmgirPDFaHcZvNGhktfR3BR4ujlIYRcCsO8eCfwZ38USlJO4ll2vftLOTvxXWxZBK/1lJS7u6x+YxNdbwZbsVuSkQrdxPmVC0+2T4liIhg0kRVvHNO1SUB+qzEVjV2EZ1C67jl99yQsh6WMR41IHTh09BOTCMUU1W27PKiHcPKr8A+VdLJ/U8O+momuxdSwXE12vtWQFptUtbtXFI4t3ZAh5Ucn2EuxLwWfKR3QnlAsweXZ6bfWPYpEGKL7mQr44lcLn6GDxFt2O7ioFMKjessSuWGnkoHbwAPQDMBE9z7mAZ1inUmJ0ojukHBZHnMgYVceVVkS7v+fVM+GSXG8G7rtYBdPRT1SHGYeSDNkpbjaFA/04dvw7OB1haS0BCL0p1eCzTKSVXC9DSOOI9OpElqY7C+tEYeAde62VFnBBOocARsvy6mxY6dP6yWasf3Gw6OyUd/qvMbwOANbfqPiwppLum1Ok4+3Kt/CgWPbIPPCm9nzJqBzLaguEyLUpzPWN+pBxnvoA052n1YZwfzWAF30oMbuUMvKF7gHhrW46mFqAP2ckYE5zaTWTrOgxR2EoipNmq0mL6S19mEV+/Yj+Xnz/zqmt/fCyvZlTbD47N7bcQakoVIwbIMkov6nnVmNRstD5oPWb7wAtb19CuiI7UM=
script:
- sudo mkdir /mvnbuild
- mvn -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -P
  cloud-integration-tests clean install -Denv.CF_API=$CF_API -Denv.CF_QA_ORGANIZATION=$CF_QA_ORGANIZATION
  -Denv.CF_QA_SPACE=$CF_QA_SPACE -Denv.CF_USERNAME=$CF_USERNAME -Denv.CF_PASSWORD=$CF_PASSWORD
- if [ $TRAVIS_TEST_RESULT -eq 0 ]; then chmod +x ./cf_blue_green_travis.sh; sudo
  add-apt-repository -y ppa:ubuntu-toolchain-r/test; sudo apt-get -qq update; sudo
  apt-get -qq install g++-4.8; sudo ./cf_blue_green_travis.sh; fi
sudo: required
